Repository squirrel-writer/squirrel, pull requests merged in 2022-02, with the labels that each got.

#15 support for python 3.8 (fixed)
  setup.py
  squirrel/xml.py
  tox.ini
Labels: enhancement, python-versions

#18 fixed typo in line 44
  squirrel/commands/overview.py
Labels: good first issue, Typo/formatting

#24 Typo
  README.md
Labels: documentation, Typo/formatting

#23 Indent function fixed
  squirrel/xml.py
Labels: bug, python-versions
